### ISSUE TITLE
[Request] VSCode

### ISSUE THREAD

**Issue by beatbox4108** [SAWARATSUKI/ServiceLogos#118]
かわいいVSCodeがほしいです！

**Comment by WhatDamon** [comment]
also need **VSCode Insider** (Green one)

**Comment by Kreijstal** [comment]
![grafik](https://github.com/SAWARATSUKI/ServiceLogos/assets/2415206/b3425d70-1ded-4315-9370-1798339c2c32)

**Comment by 0x00000FF** [comment]
https://github.com/SAWARATSUKI/ServiceLogos/tree/main/VisualStudioCode

Seems sone

**Comment by beatbox4108** [comment]
Thanks!
I'll close it.
