### ISSUE TITLE
[Request] DLang

### ISSUE THREAD

**Issue by Kapendev** [SAWARATSUKI/ServiceLogos#154]
DLang is cute. DLang wants to be more cute. Help DLang become super cute.
![Cf2CaVQVIAAujoD](https://github.com/SAWARATSUKI/ServiceLogos/assets/53071962/5fbe4e6c-e09f-4f38-9d4c-76c3e55c35b8)

**Comment by LunaTheFoxgirl** [comment]
I see you were faster than me

**Comment by kubo39** [comment]
[Goと同様に](https://github.com/SAWARATSUKI/ServiceLogos/issues/339)、プログラミング言語名は"D"なのでロゴを作っていただく際は考慮していただけるとありがたいです。

D言語およびD言語くんのライセンスについては、[D言語くんのライセンス](https://pronama.jp/2016/03/10/d-man-license/)が参考になると思います。

**Comment by kubo39** [comment]
@Kapendev According to the README, it seems that the request tag needs to be assigned. Can you please recreate the Issue?

**Comment by Kapendev** [comment]
I recreated the issue with the request label. See #441

**Comment by kubo39** [comment]
@Kapendev Thank you!

**Comment by Kapendev** [comment]
I am closing this because of #441
