### ISSUE TITLE
Add Japanese (ja) Link to README

### ISSUE THREAD

**Issue by smizuoch** [SAWARATSUKI/ServiceLogos#164]
素晴らしいロゴをありがとうございます！！

プロジェクトの改善提案があります。
現在、プロジェクトには日本語で記述されたREADMEが存在しているにも関わらず、メインのREADMEファイルからその日本語版へのリンクはありません。簡単に日本語のREADMEにアクセスできません。

日本語のREADMEへのリンクをメインのREADMEに追加することで、より多くのユーザーがプロジェクトにアクセスしやすくなると思います。

~~フォークはできる限りしないでとのことなのでissueだけ送りたいと思います。~~

**Comment by SAWARATSUKI** [comment]
PRにより対応しました！
