### ISSUE TITLE
[Request] Rename "Golang" to "Go"

### ISSUE THREAD

**Issue by ymotongpoo** [SAWARATSUKI/ServiceLogos#202]
### Check for duplicates

- [X] Checked

### Service Name

Go

### Comment

[プログラミング言語名は "Golang" ではなく "Go" なので](https://go.dev/doc/faq#go_or_golang)変更してもらいたいです。

https://github.com/SAWARATSUKI/ServiceLogos/blob/main/Go%2FGolang.png

**Comment by yui10** [comment]
こちらのissueをクローズし、修正依頼用のissueを立て直したほうが見つけられやすいと思います。

**Comment by ymotongpoo** [comment]
Thanks https://github.com/SAWARATSUKI/ServiceLogos/issues/339
