### ISSUE TITLE
[typo] KotlinのロゴがKotolinになっている

### ISSUE THREAD

**Issue by tmk815** [SAWARATSUKI/ServiceLogos#212]
## 概要
タイトル通りですが、 [こちら](https://github.com/SAWARATSUKI/ServiceLogos/tree/main/Kotlin)からダウンロードできるKotlinのロゴがKotolinになっています。

## 解決策
Xで[修正版](https://x.com/sawaratsuki1004/status/1782257675054809197)を上げてくださっているので、こちらに差し替えていただけると解決いただけると思います！

**Comment by SAWARATSUKI** [comment]
ご指摘ありがとうございます！
家に帰り次第修正します...！

**Comment by SAWARATSUKI** [comment]
修正しました！ご迷惑をおかけしました...！

**Comment by tmk815** [comment]
お忙しい中ご対応ありがとうございます🙏

**Comment by cobalto** [comment]
ただ気になったのですが、なぜKotlinのロゴが二回あるのですか
