### ISSUE TITLE
[typo]CLionの日本語表記

### ISSUE THREAD

**Issue by k-daichy** [SAWARATSUKI/ServiceLogos#216]
### 概要
CLionの日本語表記が「くりおん」になっていますがJetBrains公式の動画等を見ると「しーらいおん」と呼称しているようです。
デザイン的な意図があって現在の表記にしているのであればcloseしていただいて大丈夫です！

**Comment by SAWARATSUKI** [comment]
英語から日本語に直す際、日本語の読み方は私が普段読んでいる読み方を採用しています！
複数のissuesを頂いた場合に治して新しくアップロードします...！！
ご理解頂けると幸いです！
