### ISSUE TITLE
[Enhancement] Change `Github` to `GitHub`

### ISSUE THREAD

**Issue by Cierra-Runis** [SAWARATSUKI/ServiceLogos#218]
Official usage always is `GitHub` or `gitHub` and `github` in domain name.

**Comment by Sigumaa** [comment]
I completely agree with this suggestion!

**Comment by Kyure-A** [comment]
me too

**Comment by Cierra-Runis** [comment]
Closed.

![GitHub](https://github.com/SAWARATSUKI/ServiceLogos/blob/main/GitHub/GitHub.png?raw=true)
