### ISSUE TITLE
[Request] Emacs

### ISSUE THREAD

**Issue by torut** [SAWARATSUKI/ServiceLogos#225]
### 重複チェック

- [X] 確認しました

### サービス名

GNU Emacs （もしくは単に Emacs）

### コメント・補足

エディター界隈のきのこたけのこ戦争ではないですが、vimがあったのでEmacsもお願いしたいです。

**Comment by purin213** [comment]
[GNUEmacs/GNUEmacs.png ](https://github.com/SAWARATSUKI/ServiceLogos/blob/main/Gnuemacs/GNUEmacs.png)
に有ります

**Comment by torut** [comment]
@purin213 

ありがとうございます。
E ばかりみてました。
