### ISSUE TITLE
[typo] Javaの日本語表記が"じぁば"になっている

### ISSUE THREAD

**Issue by guraril** [SAWARATSUKI/ServiceLogos#234]
# 概要
タイトルの通り、[ここ](https://github.com/SAWARATSUKI/ServiceLogos/blob/main/Java)にあるJavaの日本語表記が「じゃば」ではなく「じぁば」になっているようです。  
こういうミームがあるならすみません。
# 解決策
間違いだった場合は書き換えていただけるとありがたいです！

**Comment by ApricotLemonTea** [comment]
「じぁば」のほうもかわいいのでヨシ(｀・ω・´)ｂ
