### ISSUE TITLE
【Request】Julia

### ISSUE THREAD

**Issue by azeredo-e** [SAWARATSUKI/ServiceLogos#24]
![Julia_Programming_Language_Logo.svg.png](https://github.com/SAWARATSUKI/ServiceLogos/assets/135235512/50bb9664-3578-4407-8933-ffd97417d448)

**Comment by CSFelix** [comment]
up

**Comment by k-haru** [comment]
age

**Comment by Makre38** [comment]
キボンヌ

**Comment by SAWARATSUKI** [comment]
added!

**Comment by azeredo-e** [comment]
ありがとう！！！
