### ISSUE TITLE
[Fix] GitHub Logo should have the letter H capitalized

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [SAWARATSUKI/ServiceLogos#305]
### Check for duplicates

- [X] Checked

### Service Name

GitHub

### Description of modifications

The H from GitHub should be capitalized based in their Logo Branding guideline

## Github Logos And Usage

[Guideline](https://github.com/logos)

![image](https://github.com/SAWARATSUKI/ServiceLogos/assets/57787993/0b94456e-4e68-439f-9720-8f3a24d6dfec)

**Comment by yui10** [comment]
類似しているissue #218
