### ISSUE TITLE
[Request] WebAssembly

### ISSUE THREAD

**Issue by fr1g** [SAWARATSUKI/ServiceLogos#420]
### Check for duplicates

- [X] Checked

### Service Name

WebAssembly, aka. WASM

### Comment

refer: 
![reference](https://seeklogo.com/images/W/web-assembly-logo-F5BFA893E6-seeklogo.com.png)

**Comment by yui10** [comment]
Related #174

**Comment by fr1g** [comment]
> Related #174

didn't got this as result while taking search before submitting issue
