### ISSUE TITLE
[Request] Common LISP

### ISSUE THREAD

**Issue by Souiken** [SAWARATSUKI/ServiceLogos#432]
### Check for duplicates

- [X] Checked

### Service Name

Common LISP

### Comment

It is a dialect of Lisp.
Different to Racket.
refer: https://common-lisp.net/

**Comment by Sinihopea** [comment]
This issue is a duplicate of:

https://github.com/SAWARATSUKI/ServiceLogos/issues/85

**Comment by SAWARATSUKI** [comment]
Done!
