### ISSUE TITLE
[Request] Scratch

### ISSUE THREAD

**Issue by rubiidev18alt** [SAWARATSUKI/ServiceLogos#440]
edit: dupe of #222, but this has more detail. so use this,

### Check for duplicates

- [X] Checked

### Service Name

Scratch

### Comment

Scratch is a high-level, block-based visual programming language and website aimed primarily at children as an educational tool, with a target audience of ages 8 to 16. Users on the site can create projects on the website using a block-like interface.
the logo/website has 2 color variations, blue and purple, blue is the og, and purple is high contrast, I want both versions.
## Reference Images
Purple:
![969551a866ced6e61e0fa72112ce5926](https://github.com/SAWARATSUKI/ServiceLogos/assets/164731988/64b5fe13-5cec-4c7c-a88e-01abb4d09f86)
![616716399ED64D299A5E](https://github.com/SAWARATSUKI/ServiceLogos/assets/164731988/0114dcc0-e2a4-4b0c-8084-d929a90090e4)
Blue:
![SCRATCH-LOGO-FONT-370x370](https://github.com/SAWARATSUKI/ServiceLogos/assets/164731988/abc72423-07bc-4ec5-8ad4-774886554b0e)

**Comment by SAWARATSUKI** [comment]
Added!

**Comment by rubiidev18alt** [comment]
about the scratch logo, edit the cat svg in the logo to have lighter outlines and sorta cuter features
