### ISSUE TITLE
【提案】 ライセンスファイルの追加

### ISSUE THREAD

**Issue by ryohidaka** [SAWARATSUKI/ServiceLogos#47]
ライセンスが無しになっていたので、追加されることを提案します。

こちら、ソースコードというより作品に当たるので、CCライセンスが適当かと思われます。

以下のサイトが参考になるかと思いますので、ご検討のほどよろしくお願いします。

- [CCライセンスについて](https://creativecommons.jp/licenses/)
- [GitHub リポジトリに CC Licenses を設定する方法](https://zenn.dev/spiegel/articles/20200919-ccl)

**Comment by Kumampet** [comment]
@ryohidaka 
PRがマージされたのでこのIssueをcloseすることを提案します。
