### ISSUE TITLE
[Request] `java.lang.NullPointerException`

### ISSUE THREAD

**Issue by sorairolake** [SAWARATSUKI/ServiceLogos#478]
### 重複チェック

- [X] 確認しました

### サービス名

`NullPointerException`

### サービス名の日本語での読み方

ぬるぽ

### コメント・補足

<https://docs.oracle.com/javase/jp/21/docs/api/java.base/java/lang/NullPointerException.html>

**Comment by maxkagamine** [comment]
ガッ！

**Comment by SAWARATSUKI** [comment]
ガッ！

**Comment by SAWARATSUKI** [comment]
追加しました！
