### ISSUE TITLE
[Request] Zig

### ISSUE THREAD

**Issue by You-saku** [SAWARATSUKI/ServiceLogos#50]
https://ziglang.org

**Comment by kassane** [comment]
@You-saku, According to the README, it seems that the request tag needs to be assigned.

Can you please recreate the Issue?

### Reference
https://github.com/SAWARATSUKI/ServiceLogos/issues/154#issuecomment-2079031380

**Comment by You-saku** [comment]
@kassane 
Thanks！I recreate this issue.
https://github.com/SAWARATSUKI/ServiceLogos/issues/545
