### ISSUE TITLE
[Request] Lua Language

### ISSUE THREAD

**Issue by WlFerrari** [SAWARATSUKI/ServiceLogos#562]
### Check for duplicates

- [X] Checked

### Service Name

Lua

### Service name in Japanese

ルア

### Comment

![Lua-not-your-average-scripting-language-blog-hero](https://github.com/SAWARATSUKI/ServiceLogos/assets/98551353/6c104354-b7c4-4943-8628-1483fa6f92eb)

**Comment by lemorage** [comment]
Dup of #91
