### ISSUE TITLE
C,C++,C# won't open

### ISSUE THREAD

**Issue by p6laris** [SAWARATSUKI/ServiceLogos#600]
Hi there.

I can't open the C,C++,C# All.png

**Comment by SAWARATSUKI** [comment]
Hi
I can open it.
Please restart your browser
![image](https://github.com/SAWARATSUKI/ServiceLogos/assets/64746703/9030c3ac-4267-43ec-98a8-7391dc20bb8f)

**Comment by Gusase** [comment]
> Hi there.
> 
> I can't open the C,C++,C# All.png

Try opening all of the files in a private browser

e.g Incognito chrome

**Comment by kongfucurry** [comment]
maybe you can try clone it into your own PC or just fork the whole repository

**Comment by p6laris** [comment]
Cloning the repo worked for me, thank you all
