### ISSUE TITLE
[Request] Discord

### ISSUE THREAD

**Issue by radian462** [SAWARATSUKI/ServiceLogos#68]
https://discord.com/branding
ロゴの申請には許可が必要なのでお手数おかけしますが宜しくお願いします。

なおロゴの編集、変更、変形、色の塗り直し、その他手を加えることは禁止事項だそうです。

**Comment by MrlolDev** [comment]
This will be awesome

**Comment by SAWARATSUKI** [comment]
追加しました！

**Comment by radian462** [comment]
ありがとうございます！
