### ISSUE TITLE
[Request] C# Remake

### ISSUE THREAD

**Issue by neko3cs** [SAWARATSUKI/ServiceLogos#70]
C#はC/C++とは同系統を追っているとは言っても似ても似つかない言語です。
むしろ、Javaに近い言語です。
なので、C/C++と一緒くたにせず、C#独自のロゴを作成頂けるとC#erとしてしあわせになります。

**Comment by Ate329** [comment]
Is this one what you want? https://github.com/SAWARATSUKI/ServiceLogos/tree/main/C%23

**Comment by neko3cs** [comment]
@Ate329 Thank you. I'll close it myself now that it's been added. 😊

**Comment by Ate329** [comment]
No problem!
